### ISSUE TITLE
Getting error "callback is not a function" with Webpack 4.10

### ISSUE THREAD

**Issue by naomiHauret** [Leocardoso94/social-tags-webpack-plugin#2]
Hi, first of all, thanks a lot for this plugin, it is really nice and helpful 👏 👍 
I'm using it on Webpack 3 projects and it works well, but using it with Webpack 4.10 doesn't work (I didn't test previous versions of Webpack).

I get the following error : 

```
  - index.js:72
  [social-tags-webpack-plugin]/dist/index.js:72:11

  - new Promise
  - Hook.js:35 AsyncSeriesWaterfallHook.lazyCompileHook [as _promise]
    [tapable]/lib/Hook.js:35:21

  - index.js:673
    [html-webpack-plugin]/index.js:673:47

  - index.js:178 Promise.resolve.then.then.then.then.then.then.html
    [html-webpack-plugin]/index.js:178:18
```

I don't think it's related to the html-webpack-plugin, I'm using both social-tags and html-plugin together in other projects and it works well.

Any help would be greatly appreciated 😄

**Comment by Leocardoso94** [comment]
Hi Naomi, I will work in a support for webpack 4, thanks for the advice!!

**Comment by Leocardoso94** [comment]
@naomiHauret can you install the version 1.0.0? I did the tests here and apparently everything is fine now

**Comment by naomiHauret** [comment]
Works perfectly ! 👌 Thank you very much! 😄
